name: Feature Request
description: Suggest a new feature or improvement for OpenPlaud
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe your idea in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: Describe the problem or use case that this feature would solve
      placeholder: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: How would you implement this?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches could solve this?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - Transcription
        - AI/LLM Integration
        - Storage (Local/S3)
        - Plaud Device Integration
        - User Interface
        - Settings/Configuration
        - Notifications
        - Export/Backup
        - Authentication
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be useful
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If applicable, add mockups, screenshots, or links to similar features in other apps

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and feature requests to avoid duplicates
          required: true
        - label: This feature aligns with OpenPlaud's goals (self-hosted, privacy-focused)
          required: true
        - label: I am willing to contribute to implementing this feature
          required: false
